#! /bin/bash

if [ $# = 0 ]
then
    echo "usage: putfile [-r] FILE [destname]"
    exit 1
fi

runflag=0
if [ "x$1" = "x-r" ]
then
    runflag=1
    shift
fi

src="$1"
shift

if [ $# = 0 ]
then
    dst=`basename $src`
else
    dst="$1"
fi

echo sending `stat --format %s $src` bytes

echo "dofile('rcvfile.lua')" > /dev/ttyUSB0
sleep 0.2

echo "rcvfile('${dst}')" > /dev/ttyUSB0
sleep 0.2

(
    IFS=""
    while read -r line
    do
	echo "$line"
	sleep 0.01
    done < $src
    # if file doesn't end in newline, add one
    tail -c 1 $src | grep . > /dev/null 2>&1
    if [ $? = 0 ]
    then
	echo ""
    fi
    # terminate transmisson with a dot on a line by itself
    echo "." 
) > /dev/ttyUSB0

if [ $runflag = 1 ]
then
    sleep 0.5
    echo "dofile('${dst}')" > /dev/ttyUSB0
fi
